AllCops:
  Exclude:
    - poc/*

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 160
  Exclude:
    - '*.gemspec'

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
