---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wd-provisioner

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: wd-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - create
      - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wd-provisioner
subjects:
  - kind: ServiceAccount
    name: wd-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: wd-provisioner
  apiGroup: rbac.authorization.k8s.io
